[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn"]

[phases.install]
cmds = ["cd frontend && yarn install"]

[phases.build]
cmds = ["cd frontend && yarn build"]

[start]
cmd = "yarn --cwd frontend start"