[build]
builder = "NIXPACKS"
buildCommand = "npm install -g yarn && cd frontend && yarn install && yarn build"

[deploy]
startCommand = "yarn --cwd frontend start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheckPath]
path = "/"
timeout = 100
REACT_APP_BACKEND_URL=http://localhost:8000