[phases.setup]
nixPkgs = ["python310", "postgresql"]

[phases.install]
cmds = ["pip install --break-system-packages -r backend/requirements.txt"]

[start]
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"