[phases.setup]
nixPkgs = ["python310Packages.pip", "python310", "postgresql"]

[phases.install]
# Install dependencies from backend folder
cmds = ["pip3 install -r backend/requirements.txt"]

[start]
# Start the FastAPI server using uvicorn
cmd = "cd backend && uvicorn server:app --host 0.0.0.0 --port $PORT"