[build]
builder = "NIXPACKS"
buildCommand = "npm install -g yarn && cd frontend && yarn install && yarn build"

[deploy]
startCommand = "yarn --cwd frontend start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10